/// DO NOT EDIT THIS FILE! Auto generated by `plugin_export`

import { plugin_t } from '@utils/types.ts';
import plug_bilibili_com from './bilibili.com/mod.ts';
import plug_ddys_art from './ddys.art/mod.ts';
import plug_douyu_com from './douyu.com/mod.ts';

const plugins: plugin_t[] = [
  plug_bilibili_com,
  plug_ddys_art,
  plug_douyu_com,
];

export default plugins;