/// DO NOT EDIT THIS FILE! Auto generated by `plugin_export`

import { plugin_t } from '@utils/types.ts';
import plug_douyu_com from './douyu.com/mod.ts'
import plug_bilibili_com from './bilibili.com/mod.ts'

const plugins: plugin_t[] = [
  plug_douyu_com,
  plug_bilibili_com,
];

export default plugins;